autoInstallPeers: true

packages:
  - apps/*
  - packages/*
  - configs/*

catalog:
  "@types/node": 24.1.0
  autoprefixer: 10.4.21
  postcss: 8.4.47
  prettier: 3.5.3
  typescript: 5.8.3
  lucide-react: 0.525.0

catalogs:
  vite-6:
    vite: 6.3.5
    vite-plugin-svgr: 4.3.0
    vite-plugin-no-bundle: 4.0.0
    vite-plugin-dts: 4.3.0
  react-19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": 19.1.0
    "@types/react-dom": 19.1.0
  react-18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": 18.3.1
    "@types/react-dom": 18.3.1
